### ISSUE TITLE
[Bug] Messages sent as Streamer don't appear in chat feed

### ISSUE THREAD

**Issue by crabcrabcam** [crowbartools/Firebot#1217] opened 2021-05-31 14:44 UTC
**Describe the bug**
Messages sent from Streamer account in the chat on dashboard don't show in the feed (but are read, and do appear on the website chat). Messages from bot account do show, as normal. 

**Steps To Reproduce**
Send a message from the streamer account in the dashboard

**Expected behavior**
Message is sent, message shows

**Firebot Version:**
5.39.2

**Computer OS:**
Linux

**Comment by ebiggz** [comment] 2021-05-31 15:53
I am unable to reproduce this issue:
![chatfeedtest](https://user-images.githubusercontent.com/3515161/120217574-27e36500-c1fe-11eb-8629-62b69d89aaa9.gif)

@brumoen I wonder if it's a linux specific issue. Could you test this and see?

**Comment by brumoen** [comment] 2021-05-31 19:11
Can't seem to reproduce on Linux either.
Tested both by chatting directly as the streamer and with command triggering chat message via the streamer account. Both works just fine.
![image](https://user-images.githubusercontent.com/4147439/120232814-a10da700-c254-11eb-9723-d0ddc2735dbd.png)

**Comment by crabcrabcam** [comment] 2021-06-01 09:29
Hmm, this is what happens for me. https://youtu.be/41QhRPvt-6I 

I've also tried logging out and relogging, just in case something was wrong with that, but still no.

**Comment by CaveMobster** [comment] 2021-09-10 10:29
@crabcrabcam Is this still an issue?

**Comment by crabcrabcam** [comment] 2021-09-10 17:28
Yes, after the updates it's still happening. I've relogged a few times
(between trying to make it work, and some password changes) so the app is
fresh. It happens on multiple setups, and on clean installs too.

**Comment by CaveMobster** [comment] 2021-09-15 11:15
@crabcrabcam Can you provide a log file?

**Comment by CaveMobster** [comment] 2022-01-16 15:47
@crabcrabcam If this is still an issue, please provide a log file. Otherwise I will be closing this issue soon.

**Closed** 2022-02-23 13:16 UTC
Labels: Bug, Needs Testing, More Info Needed
