### ISSUE TITLE
[Bug] Play Sound ignores output device setting (global and individual) when nested in Random Effect

### ISSUE THREAD

**Issue by Pigmess** [crowbartools/Firebot#1907] opened 2022-09-08 22:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I think "Play Sound ignores output device setting (global and individual) when nested in Random Effect" pretty much covers it, but please feel free to ask for clarification.

### Version

5.53.3

### What operating system are you using Firebot on?

Windows 10

### Contact Details (Optional)

Pigmess#7403

**Comment by zunderscore** [comment] 2022-09-09 01:04
I created a command, added a Random Effect to the command, then added two Play Sound effects that are each set to a different audio device inside the Random Effect playlist. Mine reliably played them randomly on their respective devices. Unfortunately, I was unable to reproduce the bug on 5.53.3.

Are you able to reliably reproduce this? If so, could you include exact steps if they differ from what I did?

**Comment by Pigmess** [comment] 2022-09-10 02:32
Steps to reproduce:

1. Create new Command or Effect List.
2. Add a Play Sound effect.
3. Set the output for that Play Sound effect to a virtual audio device, or set to "app default" and set the default output in Firebot settings to a virtual audio device.
5. Playing the sound will send it to the system default audio device regardless of selection.

I realized that the issue is tied to the use of virtual output devices - and that the Random Effect and Effect List are not necessary to reproduce it. Setting the output to a physical device circumvents the issue.

Note, I have used a virtual device as the app default in the past with no issue. My system default - where the sound is sent instead - is actually itself a virtual device.

The virtual devices in this case are created using a program called Virtual Audio Cable.

**Comment by Pigmess** [comment] 2022-09-10 02:35
Note, these latests tests I ran on Firebot 5.54.0.

Also of note, I think this behavior started after a somewhat recent update to Windows, as I found I had to re-assign my audio outputs in OBS and other programs at that time. (I have tried doing the same for Firebot - unselecting then reselecting the virtual output - to no avail. Perhaps there is a settings cache or similar that I can clear, without actually losing my settings/commands/etc?)

**Comment by zunderscore** [comment] 2022-09-10 03:33
This sounds very much like an issue with the sound devices refreshing after the Windows update and potentially needing to be reset on the effects.

Have you tried opening one of the effects that aren't working as desired, changing the output, saving and closing it with the different output, then reopening it, changing it back, and saving it a second time before testing that it works?

**Comment by Pigmess** [comment] 2022-09-10 22:29
Yes, and reconfirmed - this has no effect on the issue.

**Comment by Pigmess** [comment] 2022-09-11 04:06
Let me know if there's anything else that would be helpful to know, or whether you'd like me to provide logs/screenshots/settings.json/etc.

**Comment by zunderscore** [comment] 2022-09-13 20:17
Would you mind creating a thread in the Discord's #issues channel and referencing this issue? It might help us better troubleshoot.

**Comment by zunderscore** [comment] 2023-12-16 22:42
Checking back in. Has this been resolved? If so, I'll close the issue.

**Closed** 2023-12-24 16:48 UTC
Labels: Bug, More Info Needed
