### ISSUE TITLE
[Feature Request] Sort by name

### ISSUE THREAD

**Issue by br0kenhyperlink** [crowbartools/Firebot#2311] opened 2023-12-30 15:52 UTC
Simply put, just the option to sort commands, rewards, etc by alphabetical name a>z and z>a as well as cost, level of permission (owner, mod, then everyone) etc.

Would make it easier to find a commands and rewards or edit perms and cost

**Comment by CKY-** [comment] 2023-12-31 00:11
closing as duplicate of #1881

**Closed by CKY-** 2023-12-31 00:11 UTC
Labels: Invalid/Duplicate, Enhancement
