### ISSUE TITLE
[Bug] Toggle Connection effect for non-twitch connection fails when not logged into Streamer account.

### ISSUE THREAD

**Issue by dennisrijsdijk** [crowbartools/Firebot#2436] opened 2024-03-01 20:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you have a connection set up (eg. StreamElements) and try to start it with a Toggle Connection effect while the streamer account is NOT logged in, an error pops up that says "You must sign into your Streamer Twitch account before connecting."

### Expected Behavior

non-twitch connections should not rely on twitch for connecting with the Toggle Connection effect

### Steps To Reproduce

1. Log out of twitch accounts if logged in.
2. Authenticate to a service that has a connection (eg. StreamElements)
3. In a preset effect list, create a "Toggle Connection" effect and set it to Connect only this connection.
4. Run the preset list and observe the error

### Version

v5.61.2

### What operating system are you using Firebot on?

Linux Distro

**Comment by zunderscore** [comment] 2024-03-18 01:51
This is by design. Firebot's core functionality requires a logged-in Twitch streamer account. As the Toggle Connection effect is part of core functionality, the streamer must be logged in in order to use it. Therefore, closing this issue.

**Closed by zunderscore** 2024-03-18 01:51 UTC
Labels: Bug
