### ISSUE TITLE
[Feature Request] Allow us to export quotes. 

### ISSUE THREAD

**Issue by delolione** [crowbartools/Firebot#2582] opened 2024-06-20 01:41 UTC
**Describe the solution you'd like**
Please allow us to export quotes to a text file. 

**Additional context**
I just want a good way to backup my quotes as there are now 162 of them and if something happens, They will be lost forever. I know firebot has a backup system for all of firebot, but what if I wanted these quotes for something else? There is an import option and not having an export option feels like it is intentional to hold the quotes hostage....

**Comment by zunderscore** [comment] 2024-06-20 02:00
Duplicate of #1692

**Closed** 2024-06-20 02:00 UTC
Labels: Enhancement
