### ISSUE TITLE
[Feature Request] Save the Replay Buffer

### ISSUE THREAD

**Issue by dadthegamer** [crowbartools/Firebot#2034] opened 2023-01-19 23:38 UTC
I know this technically can be triggered via a hot key but a better option would be to save the replay buffer via OBS web socket

https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#replaybuffersaved

**Comment by dennisrijsdijk** [comment] 2023-02-01 13:32
For now, you can implement this using the **Send Raw OBS Websocket Request** effect

**Comment by zunderscore** [comment] 2023-02-03 03:01
Just realized this is a duplicate of #1955 you put in back in October, so closing this :)

**Closed by zunderscore** 2023-02-03 03:01 UTC
Labels: Invalid/Duplicate, Enhancement, Ready For Review
