### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by MattyCanny** [crowbartools/Firebot#2544] opened 2024-05-04 09:40 UTC
The ability to reorder the display order of event sets. Perhaps a 'grab' Icon, or just 'move up/down' options in the right click menu.

![image](https://github.com/crowbartools/Firebot/assets/128515589/d4795cf8-1934-4755-bf5a-f859e03eea5d)

**Comment by zunderscore** [comment] 2024-05-04 14:41
Duplicate of #2194

**Closed by zunderscore** 2024-05-04 14:41 UTC
Labels: Enhancement
