### ISSUE TITLE
[Feature Request] Support all the events from the OBS websocket

### ISSUE THREAD

**Issue by meza** [crowbartools/Firebot#2242] opened 2023-09-20 13:11 UTC
There are a lot of useful events exposed in the OBS websocket spec that are pretty useful to have.

In the first iteration, having just them exposed as is would be a great.

**Additional context**
Here are the events: https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#events

**Comment by meza** [comment] 2023-09-20 13:31
The most important one would be this: https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#sceneitemenablestatechanged

<img width="481" alt="image" src="https://github.com/crowbartools/Firebot/assets/211977/d088043d-6c95-426f-8b75-b6a94cb40995">

It basically allows us to react to source visibility changes.
The reason why it would be nice is because the Stream Deck is much more user friendly when it can show the state of a source on the button. So instead of controlling the visibility from firebot while adding additional logic to an action, we could control the visibility from buttons and then have firebot react to the visibility changes.

**Comment by CKY-** [comment] 2023-09-22 12:56
duplicate of #2209 

for now you can use the Send Raw OBS WebSockret Request for now

**Comment by meza** [comment] 2023-09-23 20:35
@CKY- I'm not sure I follow. Is there a way to register a custom listener via the websocket?

**Comment by CKY-** [comment] 2023-09-23 22:43
> @CKY- I'm not sure I follow. Is there a way to register a custom listener via the websocket?
No not listener's I need to learn to read everything and not just part of it 
We can send raw packets over to OBS that would be the Raw Request Effect

**Comment by meza** [comment] 2023-09-23 22:45
Yeah, so a poll instead of actual obs websocket events. Not ideal but it'll have to do until the OBS integration gets better I guess. Thanks for the pointer

**Comment by CKY-** [comment] 2023-09-23 23:00
The project is 100% open to PR's, I know you are busy, so for now if you dont get to it before I do I will look into adding a few more of the events.

**Comment by meza** [comment] 2023-09-23 23:32
Yeah, not sure I have the capacity to get to grips with yet another project :D
The events that might be of interest are: `Scene item visible`, `Scene item hidden`, `Switch profile`, `Switch Transition`, `Transition Begin`, `Transition End`, `Recording Starting`, `Recording Stopping`, `Replay Buffer Saved`  and `Vendor Event`

Events for enabling and disabling filters would be nice too but the UI for those could start getting very clunky so might not be worth it. It's easy to get around those with groups and dedicated scenes

**Comment by zunderscore** [comment] 2023-12-28 18:43
We certainly haven't added _all_ the events from OBS WebSocket, but I've got the ones mentioned above added, along with some variables to help out with them. They'll be in the next release.

**Closed** 2024-01-05 19:53 UTC
Labels: Enhancement, Dev Complete, Release Pending
