### ISSUE TITLE
[Feature Request] Add Command/Trigger Sets etc

### ISSUE THREAD

**Issue by Badhabits** [crowbartools/Firebot#1777] opened 2022-05-22 00:04 UTC
Event sets are really nice because one they cleanly categorized events and you can toggle the set on and off via an effect. All triggers should have this amazing feature Commands, Timers, Channel Rewards etc. Many streamers create commands/triggers that are game, stream, or even time frame specific. Being able to toggle them all Off or On on the fly would be great and since they are in a set they are all nicely organized and out of the way when not in use.  Sets should just become the standard for all triggers honestly.

**Comment by CKY-** [comment] 2022-05-23 19:58
this is a duplicate of #576

**Closed** 2022-05-23 20:03 UTC
Labels: Invalid/Duplicate, Enhancement
