### ISSUE TITLE
[V4.11.2] - Update Button Cooldown Bug

### ISSUE THREAD

**Issue by Checkmarks** [crowbartools/Firebot#619] opened 2018-05-23 16:02 UTC
## What version of Firebot are you running?
V4.11.2

## Please describe the issue or feature requests in as much detail as possible.
Any time update button effect is used to change the cooldown of a button, the button never comes off cooldown.  After the cooldown runs out, clicking the button does nothing and the moderation tab shows the click of the button and says that it is currently in cooldown when in fact it is off cooldown.  Computer time is accurate so that is not the issue.

Thanks

**Comment by Firebottle** [comment] 2018-05-28 17:50
@Checkmarks are you still having this issue?

**Comment by Checkmarks** [comment] 2018-05-31 02:37
Yes, unfortunately this issue is still present in V4.11.3.

To reproduce this issue, do the following:
1. Go to Mixer Interactive and create a button called "TEST" on default scene.
2. Save the board on Mixer and then re-sync the board on Firebot.
3. Locate the button "TEST" in your default scene in firebot and click edit on it.
4. Add Effect > Update Button
5. Select the "TEST" button from the drop-down of button choices.
6. Tick the cool down property and insert 5 seconds.
7. Save all changes.
8. Disconnect / Reconnect to firebot.
9. Try pressing the button on Mixer.  It will work the first time, but will remain in cool down even though the cool down should be over (not displayed as cooling down anymore)

NOTE:
Button cool down also does not override.  So if I put the cool down to 10 seconds in the button properties, then place an effect in that same button to update the button and set the cool down property of that to 3 seconds, the button will remain at a 10 second cool down and not get overridden.  This is true for the vise versa as well.  However, if it is a different button other than itself, then the cool down DOES get updated, however the issue above is still present where the cool down never truly comes off of whatever button is updated.

**Comment by ebiggz** [comment] 2018-05-31 07:29
Located and resolved this bug. Fix will be in the next update.

**Comment by ebiggz** [comment] 2018-05-31 07:36
Also, to speak to your note at the end of your report:
That is expected behavior due to how Firebot handles cooldowns. Cooldowns are triggered after the effect logic has been kicked off. While we dont wait for all effects to finish, if the very first effect is an Update Button effect with a cooldown that cooldown will apply and then get immediately overwritten by the cooldown assigned to the button which is why you dont see a change. 
I don't see this particular use case to be an issue as it doesn't really make sense to have a cooldown on the button while also having a Update Button effect that updates the cooldown as your first effect. The button becoming unusable after the cooldown, however, is a bug and that has been resolved. 

Anyway, thanks for the report!

**Closed** 2018-06-07 12:29 UTC
Labels: Dev Complete, bug
