### ISSUE TITLE
[BUG] Button cooldown visual bug

### ISSUE THREAD

**Issue by sorryaboutyourcats** [crowbartools/Firebot#835] opened 2020-06-08 00:19 UTC
**Describe the bug**
Cooldowns on buttons visually appear 5 seconds less, or if cooldown is under 5 seconds, have no visual change. The button remains disabled when a cooldown is happening, but visually it looks enabled.

If you set a button with an 8 second cooldown, you will see 3 seconds remaining, and after the time is up the button will appear to be enabled again, but not work until the actual cooldown [8 seconds] has been completed.

This issue is affecting both cooldown groups & individual cooldowns.

**To Reproduce**
1. Set a button with a cooldown of 8 seconds
2. Press button
3. Look at time remaining and enable/disable state

**Expected behavior**
Button should be visually disabled until the actual cooldown amount.

**Screenshots**
https://drive.google.com/drive/folders/1UjP9GFzQLFraCourblMVI0jQiLA2JABX?usp=sharing

**Video**
https://drive.google.com/file/d/1QhETiIl3U1Ab9N1zX0JSAuP1CqI1G0aS/view?usp=sharing

**Logs**
https://drive.google.com/file/d/1FiVEi5CZasoatBisYHeicAyil43sYGJn/view?usp=sharing

**Firebot Version:**
5.12.2

**Computer OS:**
Windows 10 v1909

**Browsers:**
Chrome, Edge & Firefox

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by ebiggz** [comment] 2020-06-08 16:37
Thanks for the report @sorryaboutyourcats!

An out of sync clock is the most common cause of incorrect cooldown lengths so I’d like to check that first.

When you have a chance, can you go to https://time.is and see if it’s showing your clock as being out of sync? If so, go to Windows time/clock settings and make sure “automatically set” is enabled. Or toggle it off and back on if it is already enabled.

**Comment by sorryaboutyourcats** [comment] 2020-06-08 17:14
Hey @ebiggz!

Windows had **Set time automatically** enabled, which is strange since it was 6 seconds off based on the website you linked. Funky time servers? 😬

Anyway, I was able to fix it by purchasing a flux capacitor and then forcing a resync. This has fixed the cooldown issue! 

Much thanks. ❤

**Comment by brumoen** [comment] 2020-06-08 17:55
Might want to use the official NTP servers instead of the Microsoft Time servers. I've changed to using a local NTP server and I've not seen Windows having issues syncing it's clock for ages. With the MS servers I had constant warnings in the system log about not reaching the time servers.

Duplicate of #610 by the way, which has the details about changing the time server. Just for reference since I'm pretty sure you know how to change that one on your own. ;)

**Closed by brumoen** 2020-06-08 17:55 UTC
