### ISSUE TITLE
"Add Label" field inside the effects option on top

### ISSUE THREAD

**Issue by Nashuja** [crowbartools/Firebot#1830] opened 2022-07-24 11:02 UTC
**Describe the solution you'd like**
Labels are a creat way to keep your effects organize and to be able to see exactly what each effect does. What would know be a really nice improvement would be a field on top of the pop up if you create an effect to edit the label inside that module, instead of having to save the effect, richt click on the same effect having to open another module just to edit the label.

**Comment by CKY-** [comment] 2022-07-24 14:41
this is a Duplicate of #1602

**Closed** 2022-07-29 21:20 UTC
Labels: Invalid/Duplicate, Enhancement
