### ISSUE TITLE
[Feature Request] Two PC setup, text-to-speech effect plays sound locally only and does not respect Settings > General > Sound Output Device

### ISSUE THREAD

**Issue by iamdadmin** [crowbartools/Firebot#2144] opened 2023-04-22 07:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When playing any text-to-speech effect (and I assume also the tts via amazon polly but I don't have this configured to check) the TTS output plays only on the local PC's default system sound. It does not respect Settings > General > Sound Output Device.

I have seen the feature request #1674 to add selectable options for output, and felt this issue is distinct.

### Expected Behavior

I'd expect any sounds including TTS generated by the application to respect Settings > General > Sound Output Device which in my case is Send to Overlay so it can be captured by OBS on the remote PC and broadcast.

### Steps To Reproduce

1. Create a Commands / Events / Time-based / Channel Reward and include a Text-to-Speech effect.
2. Set Settings > General > Sound Output Device to Send to Overlay.
3. Have a second PC capture the overlay in a 2 PC setup with OBS (or simply open http://other.pc.ip.addr:7274/overlay in a browser.
4. Trigger the event.
5. Note how the Text-to-Speech plays on the system's default sound output device as set in Control Panel instead of honouring Settings > General > Sound Output Device to Send to Overlay.

### Version

5.57.0

### What operating system are you using Firebot on?

Windows 10

### Relevant log output

```shell
n/a
```

**Comment by dennisrijsdijk** [comment] 2023-04-22 07:14
Text to speech (non-polly) can only play on the Firebot machine due to Microsoft TTS API. Polly TTS can be configured to play on the overlay instead.

**Comment by zunderscore** [comment] 2023-12-20 05:52
This is technically not a bug, but a limitation of available APIs. Native TTS is generated/handled by the host OS when the request is sent by a browser (in our case, the Chrome-based front end of our Electron app). Because we have no way to capture this audio, we cannot send it to an overlay. Also, OBS browser sources do not currently support native TTS, so we cannot send the TTS data to be spoken by the browser source itself.

Therefore, marking this as a feature request and closing as a duplicate of #1674.

**Closed** 2023-12-20 05:53 UTC
Labels: Invalid/Duplicate, Enhancement, Blocked
