### ISSUE TITLE
[Feature Request] Commands Page Link 

### ISSUE THREAD

**Issue by THECorranHorn** [crowbartools/Firebot#1363] opened 2021-09-08 23:28 UTC
**Describe the solution you'd like**
Add a spot in Firebot settings that shows your commands page link for ease of access when not live

**Additional context**
NA

**Comment by CaveMobster** [comment] 2022-01-08 20:05
This is not currently possible since the links change occasionally. It would mean we need to switch to static page hosting and that's not on the agenda for now.

**Comment by Firebottle** [comment] 2022-05-11 00:43
This is probably going to be a v6 issue.

**Comment by Firebottle** [comment] 2022-05-11 01:57
I'm actually going to make this as a duplicate of #1199 as once that change is made this URL will definitely appear in the app, as well as on commands, etc..

**Closed by Firebottle** 2022-05-11 01:57 UTC
Labels: Enhancement, Blocked, v6
