### ISSUE TITLE
[Feature Request] Chat message variable with all emotes removed

### ISSUE THREAD

**Issue by TheBlackParrot** [crowbartools/Firebot#1952] opened 2022-10-01 15:12 UTC
I use Firebot as a TTS bot while I'm streaming VR rhythm games so I don't have to look at a chat window while I'm playing the game, helping with interaction on my streams. I frequently run into the issue of rave-y, dance-y emotes cluttering TTS and delaying responses in messages with actual content. I don't want to completely ban emote pattern messages from my chat.
Having a variable with all emote content removed would help considerably with this issue. I'm currently sending out chat messages to my own external basic pattern recognition script to at least filter out the longer messages, but this would be a much better solution.

**Comment by CKY-** [comment] 2022-10-01 20:09
Duplicate of #1640

**Closed by CKY-** 2022-10-01 20:09 UTC
Labels: Enhancement
