### ISSUE TITLE
[Feature Request] Integrate directly with OBS

### ISSUE THREAD

**Issue by LayDwnClown** [crowbartools/Firebot#936] opened 2020-09-05 23:42 UTC
**Describe the solution you'd like**
An integration with OBS Studio where Firebot can see into firebot and control scenes

**Additional context**
This feature is asked as I currently control OBS letting Firebot send a "hotkey" command to my keyboard and within OBS Studio (Or any other broadcasting software), i have a particular scene set with a hotkey. When the command is sent from Firebot it changes to that scene. Sometimes this causes an issue, depending on what game is being played. As sometimes a game is configured to use those same keys and does something within the game as the command is sent from Firebot. So If there is integration directly to OBS this would eliminate the need for hotkeys and would solve the issue of possible overlap of game keys and hotkey commands.

**Comment by brumoen** [comment] 2020-09-06 00:17
Thanks for the suggestion, but I'll close this as it's a duplicate of #935

**Comment by SReject** [comment] 2020-09-06 00:19
Reopened: This is a more generalized request than #935 and better suits our purposes as it gives more leeway in implementation

**Comment by ebiggz** [comment] 2020-12-06 18:39
We have this functionality available as a Start Up script, get it here:
https://github.com/ebiggz/firebot-script-obs-control

**Closed** 2021-01-06 17:57 UTC
