### ISSUE TITLE
[Feature Request] Turbo viewers permission addon

### ISSUE THREAD

**Issue by coinpusherworld** [crowbartools/Firebot#2463] opened 2024-03-12 12:27 UTC
**Describe the solution you'd like**
Please can Turbo be added to permissions so that we can asign some commands to Turbo viewers.

**Additional context**
[Permissions Screenshot](https://i.imgur.com/11awRUO.png)

**Comment by CKY-** [comment] 2024-03-12 13:34
duplicate of  #2208 closing

**Closed by CKY-** 2024-03-12 13:34 UTC
Labels: Enhancement
