### ISSUE TITLE
[Feature Request] Ability to filter out usernames from the viewer list

### ISSUE THREAD

**Issue by MrCanerican** [crowbartools/Firebot#1619] opened 2022-03-09 16:53 UTC
The ability to hide specific viewers, likely by role, from the viewer list. 

This would allow bots to be hidden from the viewer list, among other potential uses

**Comment by Firebottle** [comment] 2022-05-11 00:48
This is a duplicate of #922.

**Closed by Firebottle** 2022-05-11 00:48 UTC
Labels: In Development, Enhancement
