### ISSUE TITLE
[Feature Request] Allow to manipulate data about existing Twitch users that are not known

### ISSUE THREAD

**Issue by Samuel38** [crowbartools/Firebot#1666] opened 2022-04-04 20:14 UTC
**Describe the solution you'd like**
Being able to manipulate data (ex : set user metadata) for a user that isn't in the database by letting it interrogate the Twitch API. 
Probably would require being connected to work. 

**Additional context**
For example, when importing data from some place else, you might want to enter into the database data about a user that's not been on your channel since you started using the bot. 
It would make it generally easier for new firebot users to switch to firebot seamlessly.

**Comment by zunderscore** [comment] 2022-04-04 20:16
I think this would be a duplicate of #1541

**Comment by Firebottle** [comment] 2022-05-11 00:41
Closing as a duplicate

**Closed by Firebottle** 2022-05-11 00:41 UTC
Labels: Enhancement
