### ISSUE TITLE
[Bug] Local Video's file path variable is not working.

### ISSUE THREAD

**Issue by mtane0412** [crowbartools/Firebot#2570] opened 2024-06-06 13:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using a variable for the File Path in Local Video, but the value is not being replaced.

### Expected Behavior

If there is a variable in Local Video's File Path, the value is evaluated.

### Steps To Reproduce

1, Go to Play Video in Effect
2. Select any variable in the local video file path

### Version

v5.62.1

### What operating system are you using Firebot on?

Windows 10

**Comment by CKY-** [comment] 2024-06-06 17:32
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Current Behavior
> I am using a variable for the File Path in Local Video, but the value is not being replaced.
> 
> ### Expected Behavior
> If there is a variable in Local Video's File Path, the value is evaluated.
> 
> ### Steps To Reproduce
> 1, Go to Play Video in Effect 2. Select any variable in the local video file path
> 
> ### Version
> v5.62.1
> 
> ### What operating system are you using Firebot on?
> Windows 10
> 
> ### Relevant log output
> _No response_
> 
> ### Contact Details (Optional)
> _No response_

can you show both the variable and the data you are passing into it?

**Comment by mtane0412** [comment] 2024-06-07 14:13
I used JavaScript Evaluate to return the username.
If you set the path `C://PatToDirecotry/$effectOutput[username].mp4` in Play Video, `C://PatToDirecotry/$effectOutput[username].mp4` is output to the Console The `$effectOutput[username].mp4` will be output to the Console as it is.

Then I set `$effectOutput[username]` for the chat message effect and the username was evaluated correctly.

I suspected here that the variable was not working in the file path, so I put in the appropriate variable, but the variable was still not evaluated. (e.g. $date)

**Comment by mtane0412** [comment] 2024-06-07 14:59
I found a workaround.
`$evalJs[`` return `C:\\PathToDirectory\\$effectOutput[username].mp4` ``]` works correctly.

**Comment by CKY-** [comment] 2024-06-08 07:50
correct you need to escape the \ with a \ there is not need to use evalJs like that, 

`C:\\PathToDirectory\\$effectOutput[username].mp4` 
using the path direct should work 
im going to close this as its not a bug and is more of a help request, 
if you need any other help discord is faster. 
[join discord](https://discord.gg/crowbartools-372817064034959370)

**Closed by CKY-** 2024-06-08 07:50 UTC
Labels: Bug

**Comment by mtane0412** [comment] 2024-06-08 09:31
@CKY- 
Thank you for your time!
The Path escape sequence worked correctly.
I am going to join Discord as I was having a hard time finding the documentation.
