### ISSUE TITLE
[Bug] Streamer login fails after 5.57 update

### ISSUE THREAD

**Issue by IanBigfoot** [crowbartools/Firebot#2109] opened 2023-03-10 21:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When logging back in to my Streamer account, i click on the Login button, and nothing happens. It's just a clickable button with no result. I click on the Bot Login button, the window pops up with the URL to paste into a browser, and I can log in properly. I have uninstalled/reinstalled Firebot, same thing.

Any ideas?

### Version

5.57

### What operating system are you using Firebot on?

Windows 11

**Comment by zunderscore** [comment] 2023-03-10 21:08
Closing as duplicate of #2103

**Closed by zunderscore** 2023-03-10 21:08 UTC
Labels: Bug
