### ISSUE TITLE
[Bug] Hotkey recording does not record number pad keys correctly

### ISSUE THREAD

**Issue by Geowil** [crowbartools/Firebot#2120] opened 2023-03-17 23:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When recording keystrokes for hotkeys, number pad keys are incorrectly being recorded.

If I press the "9" button on the number pad , the button should be recorded as Numpad 9.  Instead Firebot records the key press as just 9.

This causes problems when trying to interface Streambot with applications that correctly assign a virtual keypress to the correct key flag for the number pad.  Stream Decks for example.

### Expected Behavior

When recording keystrokes from the number pad, the correct key flags should be used:
Numpad 1, Numpad 2, Numpad 3, Numpad 4, Numpad 5
Numpad 6, Numpad 7, Numpad 8, Numpad 9, Numpad 0
Numpad +, Numpad -, Numpad Enter, Numpad /, Numpad *
Numpad .

### Steps To Reproduce

Start recording a hotkey selection, press any number pad key.

### Version

5.57.0

### What operating system are you using Firebot on?

Windows 10

**Comment by CKY-** [comment] 2023-03-17 23:23
duplicate of #1945

**Closed by CKY-** 2023-03-17 23:23 UTC
Labels: Bug
