### ISSUE TITLE
Effects Chat [Bug] 

### ISSUE THREAD

**Issue by NereWowi** [crowbartools/Firebot#2327] opened 2024-01-04 13:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a Channel Rewards where the effect is that the Firebot writes in the chat for me. But today it didn't work anymore.

### Version

5.59.2

### What operating system are you using Firebot on?

Windows 10

### Contact Details (Optional)

nereauwu (discord)

**Comment by zunderscore** [comment] 2024-01-04 15:04
Please create a thread in the issues channel of our Discord to diagnose this issue. As this is not a bug, but rather environmental, closing this issue.

**Closed by zunderscore** 2024-01-04 15:04 UTC
Labels: Bug
