### ISSUE TITLE
[Bug] $# Does Not Work with URL Paths in the Play Sound Effect

### ISSUE THREAD

**Issue by heyaapl** [crowbartools/Firebot#2418] opened 2024-02-21 01:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When replacing $presetArgList[] with $# in a Play Sound effect url path, the URL to the sound does not work. I have my URL path set to `https://heyaapl.com/stream/Alerts//$#alertType.mp3` (with alertType being set to `Follow`)

### Expected Behavior

If I revert to $presetArgList[alertType], it will play the sound from the URL correctly.

### Steps To Reproduce

1. Create a Preset Effect List with at least 1 argument named `alertType`
2. Add a Play Sound Effect with the URL being: https://heyaapl.com/stream/Alerts//$#alertType.mp3
3. Trigger the Preset Effect List, passing in the value to the `alertType` argument of `Follow`. No sound will play

### Version

5.61.2

### What operating system are you using Firebot on?

Other

### Contact Details (Optional)

heyaapl

**Comment by dennisrijsdijk** [comment] 2024-02-21 06:23
I feel like this is a result of the fact that the variables system now doesn't have a clear boundary between text segments. Eg. it can't know if you're looking for `$presetArgList[alertType]` or the erroneous behavior `$presetArgList[alertType.mp3]`

**Comment by zunderscore** [comment] 2024-02-23 02:51
This is by design. Periods are allowed characters in preset effect list arg names, so in this example, it's trying to use the name `alertType.mp3`, which is technically valid. When using the long version, the variable is delimited by the `[]` characters, therefore this problem does not present itself.

When using the short version where the variable is immediately followed by a period, you will need to use a `$concat` (e.g. `$concat[``https://heyaapl.com/stream/Alerts/``, $#alertType, ``.mp3``]`).

As this is working as designed, closing this issue.

**Closed by zunderscore** 2024-02-23 02:51 UTC
Labels: Bug
