### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by cj-joker** [crowbartools/Firebot#2346] opened 2024-01-07 18:51 UTC
The ability to organize via an ordered list, such as commands, events, ect... based off of the various categories they're listed under (Alphabetically based off of trigger command, cooldowns, perms, tags, enabled/disabled). 

Main concern is the ability to group everything together in order based off of Tag, without having to drag and drop each command to reorder.

**Comment by zunderscore** [comment] 2024-01-07 18:58
Duplicate of #1881

**Closed** 2024-01-07 18:58 UTC
Labels: Enhancement
