### ISSUE TITLE
[Feature Request] Countdown/Countup Overlay Effect

### ISSUE THREAD

**Issue by oErrorCode** [crowbartools/Firebot#946] opened 2020-10-06 23:58 UTC
Add a countdown count up timer that you can set the amount of time up or down to trigger on redemption of twitch channel points or be manually triggered my a mod or the streamer for a special event.

**Comment by Firebottle** [comment] 2022-05-11 01:52
Duplicate of #571

**Closed by Firebottle** 2022-05-11 01:52 UTC
Labels: Enhancement
