### ISSUE TITLE
[Bug] HTTP Request "Put Response Body in Variable" does not function as expected

### ISSUE THREAD

**Issue by mgway** [crowbartools/Firebot#1588] opened 2022-02-16 16:06 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

- When "Variable Property Path" in a HTTP Request is specified and the Variable Name is new, no variable is created
- When "Variable Property Path" in a HTTP Request is specified and the Variable Name is NOT new, the existing variable becomes mangled as the matching property is merged into the existing variable value

### Expected Behavior

- When Variable Property Path is set, a new variable should be created
- When Variable Property Path is set, subsequent runs of the effect should not merge values into the existing variable's value

### Steps To Reproduce

- Create HTTP Request
- URL: https://jsonplaceholder.typicode.com/todos/1, 
- Method: GET
- Check "Put response body in a variable"
- Variable Name: todo
- Variable Property Path: id
- Save effect
- Test effect

Observe that no new variable is created

Further,
- Edit HTTP Request
- Erase Variable Property Path
- Save effect
- Test effect

Observe that 'todo' variable is created

### Version

v5.50.3

### What operating system are you using Firebot on?

Windows 10

### Contact Details (Optional)

oh_mg#1234

**Comment by CKY-** [comment] 2022-02-17 21:21
This is working as intended, the intention here is to add to the path of an already existing object.


if  you have an object that looks like this 
```{"id":5606640252,"assigner":0,"project_id":2285391999,"section_id":0,"order":3,"content":"todo","description":"something from firebot","completed":false,"label_ids":[],"priority":1,"comment_count":0,"creator":37983788,"created":"2022-02-17T21:08:56.282916Z","url":""}```
and you set the optional path of "url" then it will add it to that path. 

```{"id":5606640252,"assigner":0,"project_id":2285391999,"section_id":0,"order":3,"content":"todo","description":"something from firebot","completed":false,"label_ids":[],"priority":1,"comment_count":0,"creator":37983788,"created":"2022-02-17T21:08:56.282916Z","url":{"id":5606644292,"assigner":0,"project_id":2285391999,"section_id":0,"order":4,"content":"todo","description":"something from firebot","completed":false,"label_ids":[],"priority":1,"comment_count":0,"creator":37983788,"created":"2022-02-17T21:10:50.573651Z","url":"https://todoist.com/"}```

the explanation of this is not well described. but it is working as intended.

**Comment by zunderscore** [comment] 2022-05-02 15:46
I think there's some confusion on how the **Variable Property Path** field works.

In this case, what you you're looking to do is to store the `id` property of the HTTP response object in the `todo` custom variable.

However, this isn't how the **Variable Property Path** field is designed. That field defines where to place the data in a property of a JSON object in a custom variable that both _already exist_ , not the path to a property in the HTTP response object. In other words, the `todo` custom variable must already exist and have a JSON object as the value. The way you have this configured now will then place the entire HTTP response in the `id` property of that JSON object.

If you want to extract the `id` of the HTTP response body, you would need to reference the previously created `todo` variable using `$customVariable[todo, id]`. That should achieve what you're looking to do.

In the meantime, as this is working as intended, I'll close this ticket.

**Closed by zunderscore** 2022-05-02 15:46 UTC
Labels: Bug
