### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by xNightWulf69** [crowbartools/Firebot#2118] opened 2023-03-17 17:53 UTC
**Describe the solution you'd like**
Enter a clear and concise description of what you want to happen.
Ability to add other Twitch Roles to users, not just custom, VIP and Mod, specifically the new Editor and Artist role. 
**Additional context**

**Comment by CKY-** [comment] 2023-03-17 23:25
duplicate of #1769

**Closed by CKY-** 2023-03-17 23:25 UTC
Labels: Enhancement
